{% set name = "pykalman" %}
{% set version = "0.9.7" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: 135779200393c6b370221990f7316740472f541346e9211d11630e2c2d8fb8a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - pykalman
    - pykalman.datasets
    - pykalman.sqrt
    - pykalman.sqrt.tests
    - pykalman.tests

about:
  home: https://pykalman.github.io
  license: BSD 3-Clause
  license_file: {{ RECIPE_DIR }}/COPYING
  license_family: BSD
  summary: 'An implementation of the Kalman Filter, Kalman Smoother, and EM algorithm in Python'
  dev_url: https://github.com/pykalman/pykalman
  doc_url: https://pykalman.github.io

extra:
  recipe-maintainers:
    - pmlandwehr
