{% set name = "pykalman" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pykalman-{{ version }}.tar.gz
  sha256: 0046d9ca7900207ca6f73b421476ba5f2e0f3e6ca1d472ff2223fd4dbd3ffdbe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - packaging
    - scikit-base <0.13.0
    - python >={{ python_min }}
    - numpy <3
    - scipy <2.0.0

test:
  imports:
    - pykalman
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pykalman.github.io
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: 'An implementation of the Kalman Filter, Kalman Smoother, and EM algorithm in Python'
  dev_url: https://github.com/pykalman/pykalman
  doc_url: https://pykalman.github.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
